version: "3.9"

services:
  localstack:
    image: 'localstack/localstack-light'
    ports:
      - '4566-4597:4566-4597'
    environment:
      - SERVICES=sqs,s3,lambda
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEBUG=1
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:8080 # Used only to allow access to Vue app
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
